### ISSUE TITLE
Odd jitter when importing SEAnims from the latest CoD (MW 2019)

### ISSUE THREAD

**Issue by One-Trick-Viper** [dtzxporter/SETools#17]
[Here is an example of the jitter that usually happens at the end of an animation](https://i.imgur.com/kcWIpKs.gifv)

Unsure what the cause is, could be exporting program but it could also be the SETools.

**Comment by ThomasCat** [comment]
This really isn't an issue. I fixed this using IK handles and I assume they do the same thing in-game. That's what the IK joints under the weapon are for. It wasn't the exporting tool.

**Comment by One-Trick-Viper** [comment]
I'm aware of this not being an issue, but the animations seems to have been fixed now.

I used to work with animations that were ported (by a friend of mine) on the day Greyhound got MW support.  I own MW myself since that time, and, the animations seem to be export perfectly fine now for me. 

I don't have anymore jitters when importing any animations. So for me it was the exporting tool, or at least I think so.

**Comment by ThomasCat** [comment]
If it was the exporting tool than every other game would be broken as it uses the exact same code. Not sure what causes it to be magically fixed on your end but if there was an update that actually fixed this wouldn't it be in the change notes for Greyhound? Some animations still jitter for me and they are supposed to as, with the way the logic works, either the entire animation is horribly broken or nothing is broken at all (unless you want to purposefully code in issues).
