### ISSUE TITLE
Maya 2022

### ISSUE THREAD

**Issue by blazinglazer** [dtzxporter/SETools#23]
Both SETools and Cast (raised this issue on that repo but you closed it... I think maybe you misunderstood) need to be updated for Maya 2022 - getting an error at line 316 in pluginWin.mel

**Comment by NaNraptor** [comment]
Having the same issue

**Comment by NaNraptor** [comment]
`global proc loadPluginCmd( string $path )
{
    if(!`pluginInfo -q -loaded $path`)
    {
        catch(`loadPlugin $path`); //<----------fails here
    }
}`

**Comment by blazinglazer** [comment]
using maya 2019 is my "fix" lol

**Comment by misteroups** [comment]
same issue... :/

**Comment by dtzxporter** [comment]
Enable 'Stack trace' in the console settings to print the warning properly

**Comment by dtzxporter** [comment]
See latest
